version: '3'
services:
  rank-api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/rank
    ports:
      - "1717:1717"
    command: bash /app/wait-for-it.sh mongodb:27017 -- bash -c "node build/server.js"
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
  web:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    restart: always
    ports:
      - "80:80"
